- name: include vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution | lower }}.yml'
    - '{{ ansible_os_family | lower }}.yml'
  tags:
    - base

- name: include tasks
  include_tasks: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution | lower }}.yml'
    - '{{ ansible_os_family | lower }}.yml'
  tags:
    - base
