# Standards: 1.2
---
- name: Install required packages
  loop: "{{ base_ubuntu_packages + base_ubuntu_additional }}"
  loop_control:
    loop_var: pkg
  package:
    name: "{{ pkg }}"
    state: present
  tags:
    - base

...
